hvm-template-beta:
	@curl -s https://s3.amazonaws.com/coreos.com/dist/aws/coreos-beta-pv.template | jq [.Mappings.RegionMap]

pv-template-beta:
	@curl -s https://s3.amazonaws.com/coreos.com/dist/aws/coreos-beta-pv.template | jq [.Mappings.RegionMap]
