postgres:
  image: postgres:9.5.0
  mem_limit: 52428800
  env_file: environment
  volumes:
    - postgres:/docker-entrypoint-initdb.d

solr:
  image: solr:5.4.1
  mem_limit: 52428800
  volumes:
    - solr:/opt/solr/server/solr
