{{^RDS}}
postgres:
  image: mdillon/postgis:9.5
  mem_limit: 209715200
  hostname: postgres
  restart: "no"
  environment:
    - POSTGRES_PASSWORD=pass
    - CKAN_DB_NAME=ckan_default
    - CKAN_DB_USER=ckan_default
    - CKAN_DATASTORE_DB_NAME=datastore_default
    - CKAN_DATASTORE_RW_DB_USER=ckan_default
    - CKAN_DATASTORE_RO_DB_USER=datastore_default
    - CKAN_DB_USER_PASS=pass
    - CKAN_DATASTORE_RW_DB_USER_PASS=pass
    - CKAN_DATASTORE_RO_DB_USER_PASS=pass
  volumes:
    - {{PWD}}/postgres:/docker-entrypoint-initdb.d
    - {{PWD}}/sbin/busybox:/sbin/busybox
{{/RDS}}

datapusher:
  image: axetwe/datapusher:0.1
  mem_limit: 50971520
  hostname: datapusher
{{^RDS}}
    - {{PWD}}/sbin/busybox:/sbin/busybox
{{/RDS}}

redis:
  image: redis:3.2.1-alpine
  mem_limit: 39715200
  hostname: redis
  volumes:
{{#RDS}}
    - /home/core/ckan/compose/sbin/busybox:/sbin/busybox
{{/RDS}}
{{^RDS}}
    - {{PWD}}/sbin/busybox:/sbin/busybox
{{/RDS}}

solr:
  image: solr:5.4.1
  mem_limit: 214572800
  hostname: solr
  volumes:
{{#RDS}}
    - /home/core/ckan/compose/solr/ckan:/opt/solr/server/solr/ckan
    - /home/core/ckan/compose/sbin/busybox:/sbin/busybox
{{/RDS}}
{{^RDS}}
    - {{PWD}}/solr/ckan:/opt/solr/server/solr/ckan
    - {{PWD}}/sbin/busybox:/sbin/busybox
{{/RDS}}

ckan:
  image: axetwe/spatial:0.5
  mem_limit: 314572800
  hostname: ckan
  ports:
    - "8000:8000"
  links:
{{^RDS}}
    - postgres:postgres
{{/RDS}}
    - solr:solr
    - redis:redis
    - datapusher:datapusher
  environment:
{{#RDS}}
    - PGUSER={{PGUSER}}
    - CKAN_SQLALCHEMY_URL=postgresql://{{CKAN_DB_USER}}:{{CKAN_DB_USER_PASS}}@{{PGHOST}}:{{PGPORT}}/{{CKAN_DB_NAME}}
    - CKAN_DATASTORE_WRITE_URL=postgresql://{{CKAN_DATASTORE_RW_DB_USER}}:{{CKAN_DATASTORE_RW_DB_USER_PASS}}@{{PGHOST}}:{{PGPORT}}/{{CKAN_DATASTORE_DB_NAME}}
    - CKAN_DATASTORE_READ_URL=postgresql://{{CKAN_DATASTORE_RO_DB_USER}}:{{CKAN_DATASTORE_RO_DB_USER_PASS}}@{{PGHOST}}:{{PGPORT}}/{{CKAN_DATASTORE_DB_NAME}}
{{/RDS}}
{{^RDS}}
    - CKAN_SQLALCHEMY_URL=postgresql://{{CKAN_DB_USER}}:{{CKAN_DB_USER_PASS}}@postgres:{{PGPORT}}/{{CKAN_DB_NAME}}
    - CKAN_DATASTORE_WRITE_URL=postgresql://{{CKAN_DATASTORE_RW_DB_USER}}:{{CKAN_DATASTORE_RW_DB_USER_PASS}}@postgres:{{PGPORT}}/{{CKAN_DATASTORE_DB_NAME}}
    - CKAN_DATASTORE_READ_URL=postgresql://{{CKAN_DATASTORE_RO_DB_USER}}:{{CKAN_DATASTORE_RO_DB_USER_PASS}}@postgres:{{PGPORT}}/{{CKAN_DATASTORE_DB_NAME}}
{{/RDS}}
  volumes:
{{#RDS}}
    - /home/core/ckan/compose/setup/production.ini:/srv/app/production.ini
    - /home/core/ckan/compose/sbin/busybox:/sbin/busybox
    - /home/core/data:/var/lib/ckan
{{/RDS}}
{{^RDS}}
    - {{PWD}}/setup/production.ini:/srv/app/production.ini
    - {{PWD}}/sbin/busybox:/sbin/busybox
    - {{PWD}}/data:/var/lib/ckan
{{/RDS}}
