{{^RDS}}
postgres:
  image: mdillon/postgis:9.5
  hostname: postgres
  restart: "no"
  environment:
    - POSTGRES_PASSWORD=pass
    - CKAN_DB_NAME=ckan_default
    - CKAN_DB_USER=ckan_default
    - CKAN_DATASTORE_DB_NAME=datastore_default
    - CKAN_DATASTORE_RW_DB_USER=ckan_default
    - CKAN_DATASTORE_RO_DB_USER=datastore_default
    - CKAN_DB_USER_PASS=pass
    - CKAN_DATASTORE_RW_DB_USER_PASS=pass
    - CKAN_DATASTORE_RO_DB_USER_PASS=pass
  volumes:
    - {{PWD}}/postgres:/docker-entrypoint-initdb.d
    - {{PWD}}/sbin/busybox:/sbin/busybox
{{/RDS}}

datapusher:
  image: axetwe/datapusher:0.1
{{#RDS}}
  mem_limit: 314572800
{{/RDS}}
  hostname: datapusher
{{^RDS}}
    - {{PWD}}/sbin/busybox:/sbin/busybox
{{/RDS}}

redis:
  image: redis:3.2.1-alpine
{{#RDS}}
  mem_limit: 39715200
{{/RDS}}
  hostname: redis
  volumes:
{{#RDS}}
    - /home/core/ckan/compose/sbin/busybox:/sbin/busybox
{{/RDS}}
{{^RDS}}
    - {{PWD}}/sbin/busybox:/sbin/busybox
{{/RDS}}

solr:
  image: solr:5.4.1
{{#RDS}}
  mem_limit: 314572800
{{/RDS}}
  hostname: solr
  volumes:
{{#RDS}}
    - /home/core/ckan/compose/solr/ckan:/opt/solr/server/solr/ckan
    - /home/core/ckan/compose/sbin/busybox:/sbin/busybox
{{/RDS}}
{{^RDS}}
    - {{PWD}}/solr/ckan:/opt/solr/server/solr/ckan
    - {{PWD}}/sbin/busybox:/sbin/busybox
{{/RDS}}

ckan:
  image: axetwe/spatial:0.5
{{#RDS}}
  mem_limit: 314572800
{{/RDS}}
  hostname: ckan
  ports:
    - "80:8000"
    - "443:8443"
  links:
{{^RDS}}
    - postgres:postgres
{{/RDS}}
    - solr:solr
    - redis:redis
    - datapusher:datapusher
  environment:
    - CKAN_OAUTH2_CLIENT_ID={{CKAN_OAUTH2_CLIENT_ID}}
    - CKAN_OAUTH2_CLIENT_SECRET={{CKAN_OAUTH2_CLIENT_SECRET}}
{{#RDS}}
    - PGUSER={{PGUSER}}
    - CKAN_SQLALCHEMY_URL=postgresql://{{CKAN_DB_USER}}:{{CKAN_DB_USER_PASS}}@{{PGHOST}}:{{PGPORT}}/{{CKAN_DB_NAME}}
    - CKAN_DATASTORE_WRITE_URL=postgresql://{{CKAN_DATASTORE_RW_DB_USER}}:{{CKAN_DATASTORE_RW_DB_USER_PASS}}@{{PGHOST}}:{{PGPORT}}/{{CKAN_DATASTORE_DB_NAME}}
    - CKAN_DATASTORE_READ_URL=postgresql://{{CKAN_DATASTORE_RO_DB_USER}}:{{CKAN_DATASTORE_RO_DB_USER_PASS}}@{{PGHOST}}:{{PGPORT}}/{{CKAN_DATASTORE_DB_NAME}}
{{/RDS}}
{{^RDS}}
    - CKAN_SQLALCHEMY_URL=postgresql://{{CKAN_DB_USER}}:{{CKAN_DB_USER_PASS}}@postgres:{{PGPORT}}/{{CKAN_DB_NAME}}
    - CKAN_DATASTORE_WRITE_URL=postgresql://{{CKAN_DATASTORE_RW_DB_USER}}:{{CKAN_DATASTORE_RW_DB_USER_PASS}}@postgres:{{PGPORT}}/{{CKAN_DATASTORE_DB_NAME}}
    - CKAN_DATASTORE_READ_URL=postgresql://{{CKAN_DATASTORE_RO_DB_USER}}:{{CKAN_DATASTORE_RO_DB_USER_PASS}}@postgres:{{PGPORT}}/{{CKAN_DATASTORE_DB_NAME}}
{{/RDS}}
  volumes:
{{#RDS}}
    - /home/core/ckan/compose/setup/production.ini:/srv/app/production.ini
    - /home/core/ckan/compose/crt:/crt
    - /home/core/ckan/compose/setup/app.conf:/srv/app/app.conf
    - /home/core/ckan/compose/setup/app.conf:/etc/supervisor/conf.d/app.conf
    - /home/core/ckan/compose/sbin/busybox:/sbin/busybox
    - /home/core/ckan/compose/setup/environment.py:/usr/local/lib/python2.7/site-packages/ckan-2.5.2-py2.7.egg/ckan/config/environment.py
    - /home/core/ckan/compose/setup/environment.py:/srv/app/src/ckan/build/lib/ckan/config/environment.py
    - /home/core/ckan/compose/setup/environment.py:/srv/app/src/ckan/ckan/config/environment.py
    - /home/core/data:/var/lib/ckan
{{/RDS}}
{{^RDS}}
    - {{PWD}}/setup/production.ini:/srv/app/production.ini
    - {{PWD}}/crt:/crt
    - {{PWD}}/setup/app.conf:/srv/app/app.conf
    - {{PWD}}/setup/app.conf:/etc/supervisor/conf.d/app.conf
    - {{PWD}}/sbin/busybox:/sbin/busybox
    - {{PWD}}/setup/environment.py:/usr/local/lib/python2.7/site-packages/ckan-2.5.2-py2.7.egg/ckan/config/environment.py
    - {{PWD}}/setup/environment.py:/srv/app/src/ckan/build/lib/ckan/config/environment.py
    - {{PWD}}/setup/environment.py:/srv/app/src/ckan/ckan/config/environment.py
    - {{PWD}}/data:/var/lib/ckan
{{/RDS}}
