postgres:
  image: postgres:9.5.0
  hostname: postgres
  env_file: environment
  volumes:
    - ./postgres/create_ckan_database_objects.sh:/docker-entrypoint-initdb.d/create_ckan_database_objects.sh
    - ./postgres/setup_remote_connections.sh:/docker-entrypoint-initdb.d/setup_remote_connections.sh

solr:
  image: solr:5.4.1
  hostname: solr
  volumes:
    - ./solr/ckan:/opt/solr/server/solr/ckan

datapusher:
  build: datapusher
  hostname: datapusher

ckan:
  image: fiware/ckan:2.5
  hostname: ckan
  ports:
    - "8000:8000"
  links:
    - postgres:postgres
    - solr:solr
    - datapusher:datapusher
  volumes:
    - ./setup/production.ini:/srv/app/production.ini
  env_file: environment
