postgres:
  image: postgres:9.5.0
  mem_limit: 209715200
  environment:
    - CKAN_SQLALCHEMY_URL=postgresql://ckan_default:pass@postgres:5432/ckan_default
    - CKAN_DATASTORE_WRITE_URL=postgresql://ckan_default:pass@postgres:5432/datastore_default
    - CKAN_DATASTORE_READ_URL=postgresql://datastore_default:pass@postgres:5432/datastore_default
  volumes:
    - /home/core/ckan/compose/postgres:/docker-entrypoint-initdb.d

solr:
  image: solr:5.4.1
  mem_limit: 209715200
  volumes:
    - /home/core/ckan/compose/solr/ckan:/opt/solr/server/solr/ckan
