postgres:
  image: postgres:9.5.0
  hostname: postgres
  env_file: environment
  volumes:
    - ./postgres/create_ckan_database_objects.sh:/docker-entrypoint-initdb.d/create_ckan_database_objects.sh
    - ./postgres/setup_remote_connections.sh:/docker-entrypoint-initdb.d/setup_remote_connections.sh

solr:
  image: solr:5.4.1
  hostname: solr
  volumes:
    - ./solr/ckan:/opt/solr/server/solr/ckan
