data:
  image: axetwe/data
  mem_limit: 2097152
  hostname: data
  restart: no

postgres:
  image: postgres:9.5.0
  mem_limit: 209715200
  hostname: postgres
  environment:
    - CKAN_SQLALCHEMY_URL
    - CKAN_DATASTORE_WRITE_URL
    - CKAN_DATASTORE_READ_URL
  volumes:
    - /home/core/ckan/compose/postgres:/docker-entrypoint-initdb.d
    - /home/core/ckan/compose/sbin/busybox:/sbin/busybox
  volumes_from:
    - data

solr:
  image: solr:5.4.1
  mem_limit: 314572800
  hostname: solr
  volumes:
    - /home/core/ckan/compose/solr/ckan:/opt/solr/server/solr/ckan
    - /home/core/ckan/compose/sbin/busybox:/sbin/busybox

ckan:
  image: fiware/ckan:2.5
  mem_limit: 314572800
  hostname: ckan
  ports:
    - "8000:8000"
  links:
    - postgres:postgres
    - solr:solr
  volumes_from:
    - data
  environment:
    - CKAN_SQLALCHEMY_URL
    - CKAN_DATASTORE_WRITE_URL
    - CKAN_DATASTORE_READ_URL
  volumes:
    - /home/core/ckan/compose/setup/production.ini:/srv/app/production.ini
    - /home/core/ckan/compose/sbin/busybox:/sbin/busybox
