CREATE ROLE ckan_default WITH LOGIN PASSWORD 'pass' NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE DATABASE ckan_default WITH OWNER ckan_default;

CREATE ROLE ckan_default WITH LOGIN PASSWORD 'pass' NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE ROLE datastore_default WITH LOGIN PASSWORD 'pass' NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE DATABASE datastore_default WITH OWNER ckan_default;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
REVOKE USAGE ON SCHEMA public FROM PUBLIC;
GRANT CREATE ON SCHEMA public TO ckan_default;
GRANT USAGE ON SCHEMA public TO ckan_default;
GRANT CREATE ON SCHEMA public TO ckan_default;
GRANT USAGE ON SCHEMA public TO ckan_default;
REVOKE CONNECT ON DATABASE ckan_default FROM datastore_default;
GRANT CONNECT ON DATABASE datastore_default TO datastore_default;
GRANT USAGE ON SCHEMA public TO datastore_default;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO datastore_default;
ALTER DEFAULT PRIVILEGES FOR USER ckan_default IN SCHEMA public
GRANT SELECT ON TABLES TO datastore_default;
