language: go
sudo: false
os:
    - linux
    - osx
go:
    - 1.4
    - 1.5
before_install: ./scripts/hack/symlink-gopath-travisci
script:
    - make test
    - make
    - ./bin/local/ecs-cli --version
